<?php
# IwaPHP CMS - Système de gestion de contenu 


###############################
# HEAD Javascripts functions  #
###############################



$head .='<script type="text/javascript" src="systeme/js.tabs.js"></script>
<script type="text/javascript" src="systeme/js.textarea.js"></script>
<script language="javascript" type="text/javascript" src="checkbb.js"></script>';
$head .= "<script language=\"JavaScript\" type=\"text/JavaScript\">\n";
$head .= "<!--\n";
$head .= "function MM_preloadImages() { \n";
$head .= "var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();\n";
$head .= "var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)\n";
$head .= "if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}\n";
$head .= "}\n";
$head .= "//-->\n";
$head .= "</script>\n";
$head .= "<script type=\"text/javascript\">\n";
$head .= "function evalPwd(s)\n";
$head .= "{\n";
$head .= "	var cmpx = 0;\n";
$head .= "	if (s.length >= 6)\n";
$head .= "	{\n";
$head .= "		cmpx++;\n";
$head .= "	if (s.search(\"[A-Z]\") != -1)\n";
$head .= "	{\n";
$head .= "	cmpx++;\n";
$head .= "	}\n";
$head .= "if (s.search(\"[0-9]\") != -1)\n";
$head .= "{\n";
$head .= "cmpx++;\n";
$head .= "}\n";
$head .= "if (s.length >= 8 || s.search(\"[\x20-\x2F\x3A-\x40\x5B-\x60\x7B-\x7E]\") != -1)\n";
$head .= "{\n";
$head .= "cmpx++;\n";
$head .= "}\n";
$head .= "}\n";
$head .= "if (cmpx == 0)\n";
$head .= "{\n";
$head .= "document.getElementById(\"weak\").className = \"nrm\";\n";
$head .= "document.getElementById(\"medium\").className = \"nrm\";\n";
$head .= "document.getElementById(\"strong\").className = \"nrm\";\n";
$head .= "}\n";
$head .= "else if (cmpx == 1)\n";
$head .= "{\n";
$head .= "document.getElementById(\"weak\").className = \"red\";\n";
$head .= "document.getElementById(\"medium\").className = \"nrm\";\n";
$head .= "document.getElementById(\"strong\").className = \"nrm\";\n";
$head .= "}\n";
$head .= "else if (cmpx == 2)\n";
$head .= "{\n";
$head .= "document.getElementById(\"weak\").className = \"yellow\";\n";
$head .= "document.getElementById(\"medium\").className = \"yellow\";\n";
$head .= "document.getElementById(\"strong\").className = \"nrm\";\n";
$head .= "}\n";
$head .= "else\n";
$head .= "{\n";
$head .= "document.getElementById(\"weak\").className = \"green\";\n";
$head .= "document.getElementById(\"medium\").className = \"green\";\n";
$head .= "document.getElementById(\"strong\").className = \"green\";\n";
$head .= "}\n";
$head .= "}\n";
$head .= "</script><script type=\"text/javascript\">\n";
$head .= "function ChangeStatut(formulaire) {\n";
$head .= "if(formulaire.regagree.checked == true) {formulaire.validation.disabled = false }\n";
$head .= "if(formulaire.regagree.checked == false) {formulaire.validation.disabled = true }\n";
$head .= "}\n";
$head .= "</script> \n";
$head .= "<script type=\"text/javascript\">\n";
$head .= "function writediv(texte)\n";
$head .= "{\n";
$head .= "document.getElementById('pseudobox').innerHTML = texte;\n";
$head .= "}\n";
$head .= "function mdpdiv(texte)\n";
$head .= "{\n";
$head .= "document.getElementById('mdpbox').innerHTML = texte;\n";
$head .= "}\n";
$head .= "function mdpokdiv(texte)\n";
$head .= "{\n";
$head .= "document.getElementById('mdpbox').innerHTML = texte;\n";
$head .= "}\n";
$head .= "function verifPseudo(pseudo)\n";
$head .= "{\n";
$head .= "if(pseudo != '')\n";
$head .= "{\n";
$head .= "if(pseudo.length<2)\n";
$head .= "writediv('<span style=\"color:#cc0000\"><b>'+pseudo+' :</b> ce pseudo est trop court</span>');\n";
$head .= "else if(pseudo.length>30)\n";
$head .= "writediv('<span style=\"color:#cc0000\"><b>'+pseudo+' :</b> ce pseudo est trop long</span>');\n";
$head .= "else if(texte = file('index.php?".$index->rootget."=verifpseudo&pseudo='+escape(pseudo)))\n";
$head .= "{\n";
$head .= "if(texte == 1)\n";
$head .= "writediv('<span style=\"color:#cc0000\"><b>'+pseudo+' :</b> ce pseudo est deja pris</span>');\n";
$head .= "else if(texte == 2)\n";
$head .= "writediv('<span style=\"color:#1A7917\"><b>'+pseudo+' :</b> ce pseudo est libre</span>');\n";
$head .= "else\n";
$head .= "writediv(texte);\n";
$head .= "}\n";
$head .= "}\n";
$head .= "}\n";
$head .= "function retapeMdp(mdp)\n";
$head .= "{\n";
$head .= "if(mdp != '')\n";
$head .= "{\n";
$head .= "if(mdp.length<2)\n";
$head .= "mdpdiv('<span style=\"color:#6699FF\">Retaper votre mot de passe pour confirmer</span>');\n";
$head .= "}\n";
$head .= "}\n";
$head .= "function retapeMdpok(mdpok)\n";
$head .= "{\n";
$head .= "if(mdpok != '')\n";
$head .= "{\n";
$head .= "if(mdpok == retapeMdp() ) {\n";
$head .= "mdpokdiv('<span style=\"color:#6699FF\">Les deux mots de passe concordent</span>');\n";
$head .= "}\n";
$head .= "}\n";
$head .= "}\n";
$head .= "function file(fichier)\n";
$head .= "{\n";
$head .= "if(window.XMLHttpRequest) // FIREFOX\n";
$head .= "xhr_object = new XMLHttpRequest();\n";
$head .= "else if(window.ActiveXObject) // IE\n";
$head .= "xhr_object = new ActiveXObject(\"Microsoft.XMLHTTP\");\n";
$head .= "else\n";
$head .= "return(false);\n";
$head .= "xhr_object.open(\"GET\", fichier, false);\n";
$head .= "xhr_object.send(null);\n";
$head .= "if(xhr_object.readyState == 4) return(xhr_object.responseText);\n";
$head .= "else return(false);\n";
$head .= "}\n";
$head .= "</script>\n";
$head .="<SCRIPT LANGUAGE=\"JavaScript\">\n";
$head .="function verifForm(formulaire)\n";
$head .="{\n";
$head .="if(formulaire.pseudo.value == \"\")\n"; 
$head .="alert('".ERROR_FORM."');\n";
$head .="else if(formulaire.password.value == \"\")\n";
$head .="alert('".ERROR_FORM."');\n"; 
$head .="else if(formulaire.mdp.value == \"\")\n";
$head .="alert('".ERROR_FORM."');\n";
$head .="else if(formulaire.verif_mdp.value == \"\")\n";
$head .="alert('".ERROR_FORM."');\n";
$head .="else if(formulaire.mail.value == \"\")\n";
$head .="alert('".ERROR_FORM."');\n";
$head .="else\n";
$head .="formulaire.submit();\n";
$head .="}\n";
$head .="</SCRIPT>\n";
$head .= "<script type=\"text/javascript\" src=\"systeme/javascripts/js.tabs.js\"></script>\n";
$head .= "<script type=\"text/javascript\" src=\"systeme/javascripts/js.textarea.js\"></script>\n";
?>